# Exercise for Unit 2

**Name:** MYRRHEA BELLE B. JUNSAY

**Date:** SEPTEMBER 12, 2025

**Year and Section:** BSCS 3A AI

## 1. Choose task

**Chosen task:** 

a.	Develop a Class in Python called Dense_Layer (included in the submitted notebook). The chosen task should have the following functions:

a) A function to setup/accept the inputs and weights

b) A function to perform the weighted sum + bias

c) A function to perform the selected activation function

d) A function to calculate the loss (predicted output vs target output)



In [1]:
import numpy as np

# d. A function to setup/accept the inputs and weights
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# c. A function to calculate the loss
def categorical_cross_entropy(y_pred, y_true):
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
    loss = -np.sum(y_true * np.log(y_pred_clipped))
    return loss

def binary_cross_entropy(y_pred, y_true):
    y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
    loss = -(y_true * np.log(y_pred_clipped) + (1 - y_true) * np.log(1 - y_pred_clipped))
    return np.mean(loss)


# Dense Layer Class
class Dense_Layer:
    
    # a. A function to setup/accept the inputs and weights
    def __init__(self, weights, biases):
        self.weights = weights
        self.biases = biases
        self.output = None

    # b. A function to perform the weighted sum + bias
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        return self.output

## 2. Problem Set

**Chosen problem set:** 

a) Given the inputs from the Iris Dataset, using the sepal length, sepal width, petal length and petal width, determine what class (Iris-setosa, Iris-versicolor, and Iris-virginica) the inputs are by calculating the output with the given the neural network configurations.

In [4]:
print("Iris Dataset Calculation\n")

# Input features
X_iris = np.array([[5.1, 3.5, 1.4, 0.2]])
# Target output 
target_iris = np.array([[0.7, 0.2, 0.1]])

# Layer 1
W1_iris = np.array([[0.2, 0.5, -0.3], [0.1, -0.2, 0.4], [-0.4, 0.3, 0.2], [0.6, -0.1, 0.5]])
B1_iris = np.array([[3.0, -2.1, 0.6]])
activation1_iris = relu

# Layer 2
W2_iris = np.array([[0.3, -0.5], [0.7, 0.2], [-0.6, 0.4]])
B2_iris = np.array([[4.3, 6.4]])
activation2_iris = sigmoid

# Layer 3 (Output) 
W3_iris = np.array([[0.5, -0.3, 0.8], [-0.2, 0.6, -0.4]])
B3_iris = np.array([[-1.5, 2.1, -3.3]])
activation3_iris = softmax

# First Hidden Layer
layer1 = Dense_Layer(W1_iris, B1_iris)
output1_raw = layer1.forward(X_iris)
output1_activated = activation1_iris(output1_raw)
print(f"Hidden Layer 1 (Output): \n{output1_activated}\n")

# Second Hidden Layer
layer2 = Dense_Layer(W2_iris, B2_iris)
output2_raw = layer2.forward(output1_activated)
output2_activated = activation2_iris(output2_raw)

print(f"Hidden Layer 2 (Output): \n{output2_activated}\n")

# Output Layer
layer3 = Dense_Layer(W3_iris, B3_iris)
output3_raw = layer3.forward(output2_activated)
final_output_iris = activation3_iris(output3_raw)

print(f"Final Predicted Output: \n{final_output_iris}\n")

# Loss Calculation
loss_iris = categorical_cross_entropy(final_output_iris, target_iris)
print(f"Loss: {loss_iris:.4f}")

predicted_class_index = np.argmax(final_output_iris)
classes = ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
print(f"\nPredicted Class: {classes[predicted_class_index]}")

Iris Dataset Calculation

Hidden Layer 1 (Output): 
[[3.93 0.15 0.85]]

Hidden Layer 2 (Output): 
[[0.99378157 0.99187781]]

Final Predicted Output: 
[[0.0265075  0.96865119 0.00484132]]

Loss: 3.0807

Predicted Class: Iris-versicolor
